services:
  nginx:
      build: ./nginx
      ports: 
        - '80:80'
        - '443:443'
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      CLIENT_ID: none
      CLIENT_SECRET: none
      DEV_MODE: enabled
      DOCKER_DEBUG: false
      REDIRECT_URI: none
      WAIT_HOSTS: mongo:27017
    ports: 
      - '8080:8080'